# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{checksum 'requirements.txt'}}
                    # Fallback case
                    - v1-dependencies-
            - run:
                name: Install dependencies.
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install
            - save_cache:
                patha:
                    - ./venv
                key: v1-dependencies-{{checksum 'requirements.txt'}}
            - run:
                name: Run lint
                command: |
                    . venv/bin/activate
                    make lint